version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env.docker
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - '80:80'
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    depends_on:
      - backend